services:
  db:
    image: postgres:15-alpine
    container_name: twitchbot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitchbot_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/init/db/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d twitchbot_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: dockerfile
    container_name: twitchbot_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/twitchbot_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
  postgres_data: