services:
  db:
    image: postgres:15-alpine
    container_name: twitchbot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitchbot_db
    ports:
      - "5432:5432"
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

volumes:
  postgres_data: